name: Deployment

# Trigger deployment on push to main (adjust as needed for your branching strategy)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup your environment (example using Node.js; adjust if needed)
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      # Example deployment step (modify commands to match your deployment process)
      - name: Deploy to Production Server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "Deploying build to production..."
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./build $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
