name: Create Release

# Trigger on tag push events that follow semantic versioning (e.g., v1.0.0)
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup your environment (example using Node.js; adjust if needed)
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      # Create a GitHub Release using an action
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - List your release notes and changes here.

      # Upload release assets (if applicable)
      - name: Upload Release Asset
        if: success() && runner.os == 'Linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/your_asset.zip  # Adjust the asset path
          asset_name: your_asset.zip          # Adjust the asset name
          asset_content_type: application/zip
